""" This code is generated by `scripts/write_images`. """
import os
import cv2


class IMAGES:

	class BS:
		FULLSCREEN_BUTTON = cv2.imread(os.path.join(*['assets', 'images', 'bs', 'fullscreen_button.png']))
		LOGO = cv2.imread(os.path.join(*['assets', 'images', 'bs', 'logo.png']))

	class COC:
		BUILDER = cv2.imread(os.path.join(*['assets', 'images', 'coc', 'builder.png']))

		class BUILDINGS:

			class OTHER:
				TOWN_HALL_1 = cv2.imread(os.path.join(*['assets', 'images', 'coc', 'buildings', 'other', 'town_hall_1.png']))
